services:
  - type: worker
    name: flex-userbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python flexuserbot.py
    envVars:
      - key: API_ID
        value: <YOUR_API_ID>
      - key: API_HASH
        value: <YOUR_API_HASH>
      - key: STRING_SESSION
        value: <YOUR_STRING_SESSION>
