services:
  - type: web
    name: flex-senzir
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: API_ID
        value: ""
      - key: API_HASH
        value: ""
      - key: STRING_SESSION
        value: ""
