services:
  - type: web
    name: flex-senzir
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: API_ID
        fromRenderer: true
      - key: API_HASH
        fromRenderer: true
      - key: STRING_SESSION
        fromRenderer: true
